version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: mlflow_postgres
    env_file:
      - database.env # PG configure
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    networks:
      - mlflow-network
    ports:
      - "5432:5432"

  mlflow:
    build:
      context: .
      dockerfile: ./mlflow.Dockerfile
    container_name: mlflow_server
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - ./data/mlruns:/mlflow/artifacts # Store MLflow artifacts locally
    depends_on:
      - postgres
    networks:
      - mlflow-network

networks:
  mlflow-network:

# volumes:
#   pgdata:
# If you want to save your results, uncomment 
# lines with "volume"