version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: mlflow_postgres
    env_file:
      - database.env # PG configure
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mlflow-network
    ports:
      - "5432:5432"

  mlflow:
    image: mlflow:latest
    container_name: mlflow_server
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/artifacts  # Store MLflow artifacts locally
    command: >
      mlflow server 
      --backend-store-uri postgresql://mlflow_user:magic_password@postgres/mlflow_db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    depends_on:
      - postgres
    networks:
      - mlflow-network

  python:
    image: python:3.12-slim
    container_name: mlflow_python
    volumes:
      - .:/app  # Mount your local directory to the container
    working_dir: /app
    networks:
      - mlflow-network
    environment:
      MLFLOW_TRACKING_URI: http://mlflow_server:5000  # Communicate with MLflow server
    depends_on:
      - mlflow

networks:
  mlflow-network:

volumes:
  pgdata:
