services:
  postgres:
    image: postgres:14
    container_name: mlflow_postgres
    env_file:
      - database.env # PG configure
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mlflow-network
    ports:
      - "5432:5432"

  mlflow:
    build:
      context: .
      dockerfile: ./mlflow.Dockerfile
    container_name: mlflow_server
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
      # - ./data/mlflow:/app/mlflow_artifacts
      - ./data:/app/data
      # - ./eda:/app/eda
      # - ./experiments:/app/experiments
    depends_on:
      - postgres
    networks:
      - mlflow-network

networks:
  mlflow-network:

volumes:
  pgdata:
# If you want to save your results, uncomment 
# lines with "volume"