name: mlflow_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - seaborn=0.13.2
  - ipykernel=6.29.5
  - jupyter
  - wheel
  - setuptools
  - pip
  - pip:
      - mlflow==2.15.1
      - pickleshare==0.7.5
      - psycopg2==2.9.9
      - kaggle
